# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5a661ba8864b0cd9c0a71218f1663fb32c76a00429c1fe4bca8975c4b22ecd782d4e0e79d3e61e95007d0b6118d1c6cb3d5301050935dcc7f6506accfe3567c

test:
  secret_key_base: 5d92111ff868991b7ede95f35f382727ce4116a3c084928aa3a7f99b1b60dae5b7e7e7978944dd6b5f077da2b34604d8288e8e957f6f19a542010dec9e0d6ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
