# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 161bd8aa89f87fd380f23eb5f5ab371a9f738d84b2318c22e40216af002d5aa59c78459179550fd29a8c60a8d60786a08b2bf39aff04fc8800e106eaa7e03b91

test:
  secret_key_base: 62d1e044b0fb5f6f3a511e36af39ce8ded51c61adba673666154a2991184cbd9c224615b361f254909ec35bcfcf4a62c2f346dceb9f163c2ee82bc76337bf528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
