default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
